apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: productcatalog-pdb
  namespace: hipster-shop
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: productcatalogservice
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: recommendation-pdb
  namespace: hipster-shop
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: recommendationservice
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: checkoutservice-pdb
  namespace: hipster-shop
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: checkoutservice
