apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tracing
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AbdurRehman924/hipster-shop.git
    targetRevision: main
    path: gitops/base/tracing
  destination:
    server: https://kubernetes.default.svc
    namespace: tracing
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
